//
//  ObscurProjectionTrainer.swift
//  FluxKit
//
//  Bootstrap P1: pretrain the shared ObscurProjection (§6 P1 of the ObscurAdapter spec)
//  with the flow-matching objective, restricted to the distilled model's own timesteps
//  (the spec's sanctioned option-2 for training against the 4-step checkpoint). Only the
//  projection (~31M params) gets gradients; the base FLUX.2 Klein weights stay frozen,
//  so backprop flows through the frozen DiT purely to reach the injected Signet branch.
//
//  Data is self-supervised: a diverse set of images generated by the base model itself,
//  each paired with its clean latent (x0, free from generation) and its DINOv2 tokens.
//  The projection learns to emit a KV bank that helps the frozen model reconstruct the
//  image it came from — i.e. a meaningful DINOv2→attention map, not the random init.
//
//  This is a bootstrap: distilled-timestep objective, model-generated data, single Mac.
//  The production run (klein-base, large real dataset, days of GPU) drops a better
//  artifact at the same path with no code change.
//

import Foundation
import CoreGraphics
import MLX
import MLXNN
import MLXRandom
import ObscurKit

public final class ObscurProjectionTrainer {
    let modelDir: URL
    let dinoWeightsURL: URL

    public struct Sample {
        let dino: MLXArray        // (256, 384) fp16
        let x0: MLXArray          // (1, imageSeq, 128) packed clean latent
        let imgIDs: MLXArray      // (imageSeq, 4)
    }

    public init(modelDirectory: URL, dinoWeightsURL: URL) {
        self.modelDir = modelDirectory
        self.dinoWeightsURL = dinoWeightsURL
    }

    /// Run bootstrap P1. Generates `prompts.count` training images, then trains the
    /// projection for `steps` optimizer steps. Returns the saved v1 artifact URL.
    public func train(prompts: [String],
                      steps: Int,
                      learningRate: Float = 1e-4,
                      resolution: Int = 256,
                      genSteps: Int = 4,
                      outputURL: URL,
                      log: (String) -> Void) throws -> URL {
        let pipeline = Flux2Pipeline(modelDirectory: modelDir)

        // ── Phase 1: build the dataset (Qwen3 + DiT + VAE + DINOv2 resident) ──
        log("• loading text encoder…")
        let encoder = try Qwen3TextEncoder(componentDir: modelDir.appendingPathComponent("text_encoder"))
        log("• precomputing empty-prompt embedding…")
        let (emptyIDs, emptyMask) = try pipeline.tokenize(prompt: " ")
        let emptyEmbeds = encoder.promptEmbeddings(inputIDs: emptyIDs, attentionMask: emptyMask)
        eval(emptyEmbeds)

        log("• loading transformer + VAE + DINOv2…")
        let dit = try Flux2Transformer(componentDir: modelDir.appendingPathComponent("transformer"))
        let vae = try Flux2VAEDecoder(componentDir: modelDir.appendingPathComponent("vae"))
        let dino = ObscurDinov2()
        try dino.loadWeights(url: dinoWeightsURL)

        let txtIDs = Flux2Pipeline.textIDs(count: emptyEmbeds.dim(1))

        var dataset: [Sample] = []
        for (i, prompt) in prompts.enumerated() {
            let (ids, mask) = try pipeline.tokenize(prompt: prompt)
            let embeds = encoder.promptEmbeddings(inputIDs: ids, attentionMask: mask)
            let (x0, packedH, packedW) = denoise(dit: dit, embeds: embeds,
                                                 seed: UInt64(1000 + i), resolution: resolution,
                                                 steps: genSteps)
            // Decode → image → DINOv2 tokens.
            let packedNCHW = x0.reshaped(1, packedH, packedW, 128).transposed(0, 3, 1, 2)
            let imageNHWC = vae.decodePacked(packedNCHW)          // (1,H,W,3) [-1,1]
            eval(imageNHWC)
            guard let cg = Self.toCGImage(imageNHWC) else { continue }
            let pixels = ObscurDinoPreprocess.input(cg)
            let tokens = dino.patchTokens(pixels)[0].asType(.float16)   // (256,384)
            eval(tokens)
            dataset.append(Sample(dino: tokens, x0: x0,
                                  imgIDs: Flux2Pipeline.latentIDs(packedH: packedH, packedW: packedW)))
            Memory.clearCache()
            log("  dataset \(i + 1)/\(prompts.count)")
        }
        guard !dataset.isEmpty else { throw FluxKitError.malformedCheckpoint("no training samples") }

        // Free the text encoder; training needs only the frozen DiT + emptyEmbeds.
        _ = encoder
        Memory.clearCache()

        // ── Phase 2: train the projection ──
        let projection = ObscurProjection(seed: 0)
        let hooked = projection.hookedLayers
        var params = projection.trainableParameters()      // fp32 source of truth
        eval(Array(params.values))

        // Distilled sigmas for this sequence length (the 4-step schedule).
        let seqLen = dataset[0].x0.dim(1)
        let scheduler = Flux2Scheduler(imageSequenceLength: seqLen, steps: genSteps)
        let sigmas = (0..<genSteps).map { scheduler.sigmas[$0] }

        // Manual Adam state.
        var m = params.mapValues { MLXArray.zeros(like: $0) }
        var vv = params.mapValues { MLXArray.zeros(like: $0) }
        let beta1: Float = 0.9, beta2: Float = 0.999, eps: Float = 1e-8

        var rngKey = MLXRandom.key(0)

        let lossFn: (ModuleParameters, Int) -> [MLXArray] = { p, idx in
            let dict = Dictionary(uniqueKeysWithValues: p.flattened())
            let sample = dataset[idx]
            let kv = ObscurProjection.projectFunctional(sample.dino, params: dict, hookedLayers: hooked)
            let composed = ObscurComposedKV.singleEntry(kv: kv, tokenCount: ObscurProjection.pooledTokens)
            let gates = ObscurGates.grouped(structure: 1, texture: 1, layers: hooked)
            let ctx = ObscurInjectionContext(composed: composed, gates: gates, recorder: nil)

            let x0 = sample.x0
            let (k1, k2) = MLXRandom.split(key: rngKey)
            rngKey = k1
            let noise = MLXRandom.normal(x0.shape, key: k2).asType(x0.dtype)
            let sigma = sigmas[idx % sigmas.count]
            let xt = (1 - sigma) * x0 + sigma * noise
            let vTarget = noise - x0
            let vPred = dit(hidden: xt, encoder: emptyEmbeds, timestep: sigma * 1000,
                            imgIDs: sample.imgIDs, txtIDs: txtIDs, adapter: ctx)
            let loss = (vPred - vTarget).square().mean()
            return [loss]
        }
        let valueAndGradFn = valueAndGrad(lossFn)

        var t = 0
        for step in 0..<steps {
            let idx = step % dataset.count
            let (values, grads) = valueAndGradFn(ModuleParameters.unflattened(params), idx)
            let gradDict = Dictionary(uniqueKeysWithValues: grads.flattened())

            t += 1
            let bc1 = 1 - pow(beta1, Float(t))
            let bc2 = 1 - pow(beta2, Float(t))
            for (key, g) in gradDict {
                m[key] = beta1 * m[key]! + (1 - beta1) * g
                vv[key] = beta2 * vv[key]! + (1 - beta2) * (g * g)
                let mhat = m[key]! / bc1
                let vhat = vv[key]! / bc2
                params[key] = params[key]! - learningRate * mhat / (sqrt(vhat) + eps)
            }
            eval(Array(params.values) + Array(m.values) + Array(vv.values))

            if step % 20 == 0 || step == steps - 1 {
                let l = values[0].item(Float.self)
                log(String(format: "  step %d/%d  loss %.5f", step, steps, l))
            }
            Memory.clearCache()
        }

        projection.setTrainableParameters(params)
        try projection.save(to: outputURL)
        log("✓ saved projection → \(outputURL.path)")
        return outputURL
    }

    // MARK: - Denoise (captures x0)

    /// Run the 4-step denoise loop; returns (x0 packed (1,seq,128), packedH, packedW).
    func denoise(dit: Flux2Transformer, embeds: MLXArray, seed: UInt64,
                 resolution: Int, steps: Int) -> (MLXArray, Int, Int) {
        let latentH = 2 * (resolution / 16)
        let latentW = 2 * (resolution / 16)
        let packedH = latentH / 2
        let packedW = latentW / 2
        let imageSeq = packedH * packedW

        var latents = MLXRandom.normal([1, 128, packedH, packedW], key: MLXRandom.key(seed))
            .asType(Flux2Pipeline.activationDType)
            .reshaped(1, 128, imageSeq)
            .transposed(0, 2, 1)
        let imgIDs = Flux2Pipeline.latentIDs(packedH: packedH, packedW: packedW)
        let txtIDs = Flux2Pipeline.textIDs(count: embeds.dim(1))
        let scheduler = Flux2Scheduler(imageSequenceLength: imageSeq, steps: steps)

        for i in 0..<steps {
            let noise = dit(hidden: latents, encoder: embeds, timestep: scheduler.timesteps[i],
                            imgIDs: imgIDs, txtIDs: txtIDs, adapter: nil)
            latents = scheduler.step(noise: noise, latents: latents, index: i)
            eval(latents)
        }
        return (latents, packedH, packedW)
    }

    static func toCGImage(_ image: MLXArray) -> CGImage? {
        try? Flux2Pipeline.toCGImage(image)
    }
}
